# Generated by Django 6.0.3 on 2026-04-02 22:18

import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIngredient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('dough', 'Dough'), ('sauce', 'Sauce'), ('cheese', 'Cheese'), ('topping', 'Topping'), ('extra', 'Extra')], max_length=50)),
                ('sub_type', models.CharField(blank=True, help_text='For topping variants', max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Main ingredient image', max_length=500, null=True)),
                ('piece_image_url', models.URLField(blank=True, help_text='Piece/detail image', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ingredient',
                'verbose_name_plural': 'historical ingredients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('pizza', 'Pizza'), ('drink', 'Drink'), ('salad', 'Salad'), ('sides', 'Sides'), ('other', 'Other')], max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Primary product image', max_length=500, null=True)),
                ('piece_image_url', models.URLField(blank=True, help_text='Product detail image', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(default=3)),
                ('safety_stock_days', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('dough', 'Dough'), ('sauce', 'Sauce'), ('cheese', 'Cheese'), ('topping', 'Topping'), ('extra', 'Extra')], max_length=50)),
                ('sub_type', models.CharField(blank=True, help_text='For topping variants', max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Main ingredient image', max_length=500, null=True)),
                ('piece_image_url', models.URLField(blank=True, help_text='Piece/detail image', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('pizza', 'Pizza'), ('drink', 'Drink'), ('salad', 'Salad'), ('sides', 'Sides'), ('other', 'Other')], max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Primary product image', max_length=500, null=True)),
                ('piece_image_url', models.URLField(blank=True, help_text='Product detail image', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(default=3)),
                ('safety_stock_days', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
