# Generated by Django 6.0.3 on 2026-04-02 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('sub_type__isnull', True), ('type', 'topping'), _connector='OR'), name='ingredient_sub_type_requires_topping'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='cheese',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'cheese'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='dough',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'dough'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='sauce',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'sauce'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='cheese',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'cheese'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_cheese_for', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='dough',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'dough'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_dough_for', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='extras',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'extra'}, related_name='as_extra_for', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='sauce',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'sauce'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_sauce_for', to='pizza_management.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'topping'}, related_name='as_topping_for', to='pizza_management.ingredient'),
        ),
    ]
