# Generated by Django 6.0.3 on 2026-04-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='original_price',
            field=models.FloatField(blank=True, help_text='Original price for rollback', null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='original_price',
            field=models.FloatField(blank=True, help_text='Original price for rollback', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='original_price',
            field=models.FloatField(blank=True, help_text='Original price for rollback', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.FloatField(blank=True, help_text='Original price for rollback', null=True),
        ),
    ]
