# Generated by Django 6.0.3 on 2026-04-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_management', '0003_historicalingredient_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='sub_type',
            field=models.CharField(blank=True, help_text='Item variant (small, medium, large, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_type',
            field=models.CharField(blank=True, help_text='Item variant (small, medium, large, etc.)', max_length=50, null=True),
        ),
    ]
