# Generated by Django 6.0.3 on 2026-04-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_management', '0007_historicalitem_created_by_historicalitem_is_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='piece_image_url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='piece_image_url',
        ),
    ]
