# Generated by Django 6.0.3 on 2026-04-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_management', '0008_remove_historicalitem_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='safety_stock_days',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='safety_stock_days',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock_quantity',
        ),
    ]
