# Generated by Django 6.0.3 on 2026-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_management', '0009_remove_historicalitem_lead_time_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingredient',
            name='image_source_url',
            field=models.CharField(blank=True, help_text='Source path for backup (e.g., assets/images/...)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalingredient',
            name='piece_image_source_url',
            field=models.CharField(blank=True, help_text='Source path for piece image backup', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='image_source_url',
            field=models.CharField(blank=True, help_text='Source path for backup (e.g., assets/images/pizza/...)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_source_url',
            field=models.CharField(blank=True, help_text='Source path for backup (e.g., assets/images/...)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='piece_image_source_url',
            field=models.CharField(blank=True, help_text='Source path for piece image backup', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_source_url',
            field=models.CharField(blank=True, help_text='Source path for backup (e.g., assets/images/pizza/...)', max_length=500, null=True),
        ),
    ]
