# Generated by Django 6.0.3 on 2026-06-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_management', '0010_historicalingredient_image_source_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
