"""
Django settings for backend_dj project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys
import firebase_admin
from firebase_admin import credentials
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

env_path = Path(".env")

print("Loading .env from:", env_path.resolve())
if not env_path.exists():
    print("ERROR: .env not found at that path"); sys.exit(1)

load_dotenv(env_path)

# for line in env_path.read_text().splitlines():
#     s=line.strip()
#     if not s or s.startswith("#"): continue
#     k = s.split("=",1)[0].strip()
#     print(f"{k} = {os.getenv(k)!r}")


SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',  # Channels ASGI server
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "channels",  # Django Channels for WebSocket
    "api",  # Health check and other API utilities
    "pizza_management",
    "order_management",
    "user_management",
    "delivery_management",
    "stock_management",
    "payment_management",
    'simple_history',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_management.middleware.TokenRefreshMiddleware',
]

ROOT_URLCONF = 'backend_dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_dj.wsgi.application'


# Database: use SQLite in DEBUG, Postgres otherwise
if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "pizza_ordering_db"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", "your_password"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
  "http://localhost:3000",
  "http://127.0.0.1:3000",
  "http://localhost:5173",
  "http://127.0.0.1:5173",
  "http://localhost:5174",
  "http://127.0.0.1:5174",
  "http://localhost:5175",
  "http://127.0.0.1:5175",
]
# Nếu dùng cookie-based auth (send credentials):
CORS_ALLOW_CREDENTIALS = True

# Expose custom headers to frontend JavaScript
CORS_EXPOSE_HEADERS = ["X-New-Access-Token"]

# ✅ FIX: Cookie settings for cross-origin requests
SESSION_COOKIE_SECURE = False  # Set True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Lax for localhost development
SESSION_COOKIE_DOMAIN = None  # Allow all subdomains/hosts

REST_FRAMEWORK = {
  "DEFAULT_AUTHENTICATION_CLASSES": (
    "user_management.authentication.CookieJWTAuthentication",
  ),
  "DEFAULT_THROTTLE_CLASSES": [
    "rest_framework.throttling.AnonRateThrottle",
    "rest_framework.throttling.UserRateThrottle",
  ],
  "DEFAULT_THROTTLE_RATES": {
    "anon":                  "60/min",   # anonymous API access
    "user":                  "600/min",  # authenticated user general
    "user_list":             "60/min",   # GET /api/users/ per user
    "user_list_ip":          "30/min",   # GET /api/users/ per IP (unauthenticated guard)
    "change_password_user": "5/hour",   # max 5 password changes per user per hour
    "change_password_ip":   "20/hour",  # max 20 attempts per IP per hour
  },
  "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
  "PAGE_SIZE": 20,
}
from datetime import timedelta
SIMPLE_JWT = {
  "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
  "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
  "ROTATE_REFRESH_TOKENS": True,
  "BLACKLIST_AFTER_ROTATION": True,
}

# Add this line (before any migrations)
AUTH_USER_MODEL = 'user_management.User'

# ======================
# REDIS CACHE CONFIGURATION
# ======================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,  # Don't crash if Redis is down
        }
    }
}

# Cache timeout settings (in seconds)
CACHE_TIMEOUT_ITEMS = 300  # 5 minutes for item list/filter
CACHE_TIMEOUT_USER = 600   # 10 minutes for user data
CACHE_TIMEOUT_CONFIG = 3600  # 1 hour for config data

# ======================
# LOGGING CONFIGURATION
# ======================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],  # Only show in DEBUG mode
        },
        'console_production': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_false'],  # Only show in production
        },
    },
    'loggers': {
        'user_management': {
            'handlers': ['console', 'console_production'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ======================
# FIREBASE CONFIGURATION
# ======================
import firebase_admin
from firebase_admin import credentials

# ======================
# MEDIA FILES / STORAGE
# ======================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Optional: Use Firebase as default storage backend for FileField
# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# GS_BUCKET_NAME = 'your-project.appspot.com'

# ======================
# CELERY CONFIGURATION
# ======================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery Beat schedule is defined in backend_dj/celery_app.py
# See: https://docs.celeryproject.io/en/stable/userguide/periodic-tasks.html

# ======================
# EMAIL CONFIGURATION
# ======================
# Use console backend locally; set EMAIL_BACKEND=smtp in .env / prod environment.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@pizzaadmin.local')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'

# ======================
# RATE LIMITING — set True to bypass all @rate_limit checks (testing only)
DISABLE_RATE_LIMIT = False

# PAYMENT / REFUND ANTI-ABUSE
# ======================
REFUND_RATE_LIMIT = 5           # max refund requests per IP per window
REFUND_RATE_WINDOW = 3600       # window in seconds (1 hour)
REFUND_ABUSE_THRESHOLD = 3      # violations before IP is flagged as abusive

AUTO_REFUND_MAX_AGE_MINUTES = 10    # auto-approve only if payment is this fresh
AUTO_REFUND_MAX_AMOUNT = 500000     # auto-approve cap (VND)
AUTO_REFUND_MAX_RISK = 20           # risk_score must be below this to auto-approve

RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')  # set in .env
RECAPTCHA_SCORE_THRESHOLD = 0.5
RECAPTCHA_ENABLED = True  # set False in dev/test to skip CAPTCHA verification

# ======================
# CHANNELS/WEBSOCKET CONFIGURATION
# ======================
ASGI_APPLICATION = "backend_dj.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }

# ======================
# STORAGE CONFIGURATION
# ======================
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Storage type: 'local' or 'firebase' (independent of DEBUG)
STORAGE_TYPE = os.getenv("STORAGE_TYPE", "firebase").lower()
USE_LOCAL_STORAGE = STORAGE_TYPE == "local"

# Firebase initialized only if using Firebase storage
FIREBASE_ENABLED = os.getenv("DISABLE_FIREBASE", "1") != "1" and not USE_LOCAL_STORAGE

if FIREBASE_ENABLED:
    bucket = os.getenv("FIREBASE_STORAGE_BUCKET")
    cred_path = os.getenv("FIREBASE_CREDENTIALS_PATH")
    if cred_path:
        cred = credentials.Certificate(cred_path)
        firebase_admin.initialize_app(cred, {"storageBucket": bucket})