# Generated by Django 6.0.3 on 2026-04-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_orderitem_customizations_orderitem_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price_at_order',
        ),
    ]
