# Generated by Django 6.0.3 on 2026-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_remove_orderitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee charged for cancellation (20% of total for preparing orders)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Reason for order cancellation', max_length=255, null=True),
        ),
    ]
