# Generated by Django 6.0.3 on 2026-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_add_task_roletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_receive_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_stock_take',
            field=models.BooleanField(default=False),
        ),
    ]
