# Generated by Django 6.0.3 on 2026-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_add_shift_task_permission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workschedule',
            new_name='user_manage_assigne_dc8dec_idx',
            old_name='usermgmt_ws_assigned_week_idx',
        ),
        migrations.RenameIndex(
            model_name='workschedule',
            new_name='user_manage_created_abe757_idx',
            old_name='usermgmt_ws_creator_week_idx',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='entries',
            field=models.JSONField(default=dict, help_text='Map weekday→shift, e.g. {"mon": "08:00-16:00", "tue": "off"}'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='week_start',
            field=models.DateField(help_text='Monday of the week this schedule covers (YYYY-MM-DD)'),
        ),
    ]
