# Generated by Django 6.0.3 on 2026-04-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Primary supplier for this item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock_management.provider'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Primary supplier for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='stock_management.provider'),
        ),
    ]
