# Generated by Django 6.0.3 on 2026-04-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_historicalinventory_provider_inventory_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='stock_management.inventory'),
        ),
    ]
