# Generated by Django 6.0.3 on 2026-05-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_alter_purchaseorderitem_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='reason',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reason_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reason_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('stock_take', 'Stock Take')], default='stock_take', max_length=20),
        ),
    ]
