# Generated by Django 6.0.3 on 2026-05-02 03:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0004_inventorylog_reason_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTakeSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('stock_take', 'Stock Take'), ('receipt', 'Receipt')], default='stock_take', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional hard deadline; null = no expiry', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member currently responsible for the session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(help_text='Manager/admin who opened the session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='stock_manag_status_ec861f_idx'), models.Index(fields=['assigned_to', 'status'], name='stock_manag_assigne_6daa8d_idx')],
            },
        ),
    ]
