# Generated by Django 6.0.3 on 2026-05-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0002_refund_fee_refund_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Why this status change occurred (e.g., "Payment gateway approval", "Customer cancelled")', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context like error codes, gateway responses, or retry info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='payment_management.payment')),
            ],
            options={
                'verbose_name': 'Payment Phase',
                'verbose_name_plural': 'Payment Phases',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['payment', 'created_at'], name='payment_man_payment_75f6b9_idx')],
            },
        ),
    ]
